# Generated by Django 2.2.2 on 2019-06-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcm_django', '0004_auto_20181128_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('fcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fcm_django.FCMDevice')),
                ('tags', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'FCM device',
                'abstract': False,
            },
            bases=('fcm_django.fcmdevice',),
        ),
    ]
