# Generated by Django 2.2.2 on 2019-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0004_auto_20181128_1642'),
        ('firebase_notificiation', '0002_auto_20190624_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=255)),
                ('devices', models.ManyToManyField(related_name='tags', to='fcm_django.FCMDevice')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceModel',
        ),
    ]
