version: '3'
services:
  web:
    build: ./django_firebase
    volumes:
      - ./django_firebase:/codebase
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS}"
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5442:5432
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
 